Updated Contributing.md
muonium/translations pull request #6
Opened 2017-03-26 13:36 UTC by N3tt3rm4n

I added some code style preferences ;) Please change them if you don't like them :sunglasses: 

Btw I will have a closer look at the translations in core in the following days 'cause I don't have much time today

2017-03-26 13:56 UTC, Super-Baleine commented
okay x)

2017-03-26 14:01 UTC, Super-Baleine requested changes
Precise "indent mode 4 ..." for the GitHub's web code editor

2017-03-26 14:01 UTC, Super-Baleine commented on CONTRIBUTING.md
> +Please use following style: Intend mode `Spaces` and Intend size `4`. If you have done this (you can adjust that at the top of the file right of `Edit file`) you can use tabs, they automatically will
For the GitHub's web editor. You've to precise x)

2017-03-27 15:04 UTC, N3tt3rm4n commented
Like that?

2017-03-27 17:45 UTC, Super-Baleine approved these changes
Good.

2017-03-27 17:46 UTC, merged

2017-03-27 17:46 UTC, Super-Baleine commented
Thanks man!